name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Fix permissions and Build
      run: |
        cd TV7iptv_AndroidProject/TV7iptv
        chmod +x gradlew
        ./gradlew wrapper --gradle-version 8.0
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: TV7iptv_AndroidProject/TV7iptv/app/build/outputs/apk/debug/*.apk
